name: Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install Dependencies
        run: |
          poetry install
      - name: Run Unit Tests
        run: |
          poetry run python -m unittest discover -s tests/ -p 'test_*.py'
